name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

      - name: Run all tests 🧪
        run: |
          npx cypress-expect \
            --passing 4 --pending 0

      # there should be 1 test with "hello" substring
      # and 3 other tests that will be pending
      - name: Run tests with "hello" 🧪
        run: |
          npx cypress-expect run \
            --env grep=hello \
            --expect ./expects/hello.json

      - name: Run tests with "@tag1" 🧪
        run: |
          npx cypress-expect run \
            --env grep=@tag1 \
            --expect ./expects/tag1.json

      - name: Run tests with "@tag2" 🧪
        run: |
          npx cypress-expect \
            --env grep=@tag2 \
            --expect ./expects/tag2.json

      - name: Run tests with "does-not-exist-tag" 🧪
        run: |
          npx cypress-expect \
            --env grep=does-not-exist-tag \
            --expect ./expects/all-pending.json

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
