name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@2
      - name: Install dependencies 📦
        uses: cypress-io/github-action@v2
        with:
          # just perform install
          runTests: false

      # there should be 1 test with "hello" substring
      # and 3 other tests that will be pending
      - name: Run tests with "hello" 🧪
        run: npx cypress-expect --passing 1 --pending 3 --env grep=hello
